// Generated by the WOLips Templateengine Plug-in at 26 oct. 2020 14:47:03
package your.app;

import com.webobjects.appserver.WOSession;

public class Session extends WOSession {
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
