// Generated by the WOLips Templateengine Plug-in at 26 oct. 2020 14:47:03
package your.app.components;

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class Main extends WOComponent {
	private static final long serialVersionUID = 1L;

	public Main(WOContext context) {
		super(context);
	}
	
	public String searchText;

	public WOActionResults searchButton() {
		
		return null;
	}
}
